IS_0_3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from log.views import index_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_login, name='index_login'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('log/', include('log.urls')),
    path('register/', include('register.urls')), # 引入register应用的urls.py
    path('customer/', include('customer.urls')), # 引入customer应用的urls.py
    path('customerservice/', include('customerservice.urls')), # 引入customerservice应用的urls.py
    path('inventory/', include('inventory.urls')), # 引入inventory应用的urls.py
    path('aftersales/', include('aftersales.urls')), # 引入aftersales应用的urls.py
    path('blog/', include('blog.urls')), # 引入blog应用的urls.py
    path('ckeditor/', include('ckeditor_uploader.urls')), # 引入ckeditor应用的urls.py
    path('map/', include('map.urls')), # 引入map应用的urls.py
    path('chat/', include('chat.urls')),  # 引入chat应用的urls.py



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'


urlpatterns = [
    path('posts/lists', views.post_list, name='post_list'),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', views.comment_post, name='comment_post'),
    path('posts/<int:post_id>/share/', views.share_post, name='share_post'),
    path('search/', views.search_posts, name='search_posts'),
    path('users/<int:user_id>/', views.user_profile, name='user_profile'),
    path('users/<int:user_id>/followers/', views.follower_list, name='follower_list'),
    path('users/<int:user_id>/following/', views.following_list, name='following_list'),
    path('posts/<int:post_id>/likes/', views.post_likes, name='post_likes'),
    path('posts/<int:post_id>/comments/', views.comments_list, name='comments_list'),
    path('like/<int:post_id>', views.like_post, name='like_post'),
    path('follow/<int:user_id>', views.follow_user, name='follow_user'),



]

log/urls.py
from django.urls import path
from log.views import logout_view, index_login, profile, services, team

urlpatterns = [
    path('', index_login, name='index_login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
    path('services/', services, name='services'),
    path('team/', team, name='team'),
]

blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
from register.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('标题',max_length=100)
    content = RichTextUploadingField('内容',blank=False)
    image = models.ImageField('图片',upload_to='blog/images/', null=True, blank=True)
    video = models.FileField('视频',upload_to='blog/videos/', null=True, blank=True)
    created_at = models.DateTimeField('创建时间',auto_now_add=True)
    updated_at = models.DateTimeField('更新时间',auto_now=True)
    shares = models.PositiveIntegerField('分享',default=0)
    tags = TaggableManager('标签',blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} commented on {self.post.title}'


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('follower', 'following')

    def __str__(self):
        return f'{self.follower.username} follows {self.following.username}'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f'{self.user.username} likes {self.post.title}'

blog/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'video', 'tags']  # 添加'tags'字段

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from taggit.models import Tag
from django.core.paginator import Paginator
from blog.forms import PostForm
from blog.models import Post, Comment, Follow, Like
from register.models import User


def post_list(request):
    tag_slug = request.GET.get('tag')
    if tag_slug:
        posts = Post.objects.filter(tags__slug=tag_slug)
    else:
        posts = Post.objects.all()

    paginator = Paginator(posts, 2)  # 每页显示 2 篇文章

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    tags = Tag.objects.all()
    return render(request, 'post_list.html', {'page_obj': page_obj, 'tags': tags})



from django.utils.safestring import mark_safe

def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.content = mark_safe(post.content)  # 将博客内容标记为安全内容
    likes_count = Like.objects.filter(post=post).count()
    comments_count = Comment.objects.filter(post=post).count()
    shares = post.shares

    return render(request, 'post_detail.html', {
        'post': post,
        'shares': shares,
        'likes_count': likes_count,
        'comments_count': comments_count,
    })



def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            tags = form.cleaned_data.get('tags')
            form.save_m2m()  # 保存 ManyToMany 字段的关联数据
            return redirect('blog:post_list')
    else:
        form = PostForm()
    return render(request, 'create_post.html', {'form': form})


@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    # 检查是否已经点赞
    if Like.objects.filter(user=user, post=post).exists():
        # 如果已经点赞，执行取消点赞操作
        Like.objects.filter(user=user, post=post).delete()
    else:
        # 如果尚未点赞，执行点赞操作
        Like.objects.create(user=user, post=post)

    return redirect('blog:post_detail', post_id=post_id)


@login_required
def comment_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    content = request.POST.get('content')

    if not content:
        error_message = "评论内容不能为空"
        return render(request, 'post_detail.html',
                      {'post': post, 'shares': post.shares, 'error_message': error_message})

    Comment.objects.create(user=user, post=post, content=content)

    return redirect('blog:post_detail', post_id=post_id)


def share_post(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        post.shares += 1
        post.save()
    return redirect('blog:post_detail', post_id=post_id)


def user_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    posts = Post.objects.filter(author=user)
    followers = user.get_followers()
    following = user.get_following()
    return render(request, 'user_profile.html',
                  {'user': user, 'followers': followers, 'following': following, 'posts': posts})


def search_posts(request):
    query = request.GET.get('q')
    posts = None

    if query:
        posts = Post.objects.filter(title__icontains=query)

    return render(request, 'search_results.html', {'query': query, 'posts': posts})


@login_required
def follow_user(request, user_id):
    following_user = get_object_or_404(User, id=user_id)
    follower_user = request.user

    # 检查是否已经关注
    if Follow.objects.filter(follower=follower_user, following=following_user).exists():
        # 如果已经关注，执行取消关注操作
        Follow.objects.filter(follower=follower_user, following=following_user).delete()
    else:
        # 如果尚未关注，执行关注操作
        Follow.objects.create(follower=follower_user, following=following_user)

    return redirect('blog:user_profile', user_id=user_id)


def follower_list(request, user_id):
    user = get_object_or_404(User, id=user_id)
    followers = user.get_followers()
    return render(request, 'followers_list.html', {'user': user, 'followers': followers})


def following_list(request, user_id):
    user = get_object_or_404(User, id=user_id)
    following = user.get_following()
    return render(request, 'following_list.html', {'user': user, 'following': following})


def post_likes(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    likes = Like.objects.filter(post=post)
    return render(request, 'likes_list.html', {'post': post, 'likes': likes})


def comments_list(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # 获取评论对象列表
    comments = Comment.objects.filter(post=post)

    # 使用分页器对评论进行分页
    paginator = Paginator(comments, 2)  # 每页显示 2 条评论

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'comments_list.html', {'post': post, 'comments': comments, 'page_obj': page_obj})

blog/templates/comments_list.html
{% extends 'base_customer.html' %}
{% block title %}车友圈/评论{% endblock %}
{% block content %}
<style>
    .comment-h2 {
        text-align: center;
    }
</style>

<h2>评论</h2>

<!-- 评论表单 -->
{% if request.user.is_authenticated %}
    <form id="comment-form" method="post" action="{% url 'blog:comment_post' post_id=post.id %}">
        {% csrf_token %}
        <label>
            <textarea name="content" id="comment-content" rows="4" cols="50"></textarea>
        </label>
        <p id="comment-error" style="color: red;"></p>
        <button type="submit" onclick="validateComment()">评论</button>
    </form>
{% endif %}

<script>
    function validateComment() {
        var commentContent = document.getElementById('comment-content').value;
        var errorElement = document.getElementById('comment-error');

        if (commentContent.trim() === '') {
            errorElement.textContent = '评论内容不能为空';
            event.preventDefault(); // Prevent form submission if the comment is empty
        } else {
            errorElement.textContent = '';
        }
    }
</script>

<!-- 显示评论 -->
<h2 class="comment-h2">具体评论内容</h2>
{% for comment in page_obj %}
    <p>{{ comment.content }}</p>
    <p>作者：<a href="{% url 'blog:user_profile' user_id=comment.user.id %}">{{ comment.user.username }}</a></p>
    <p>发表时间：{{ comment.created_at }}</p>
    <hr>
{% empty %}
    <p>暂无评论。</p>
{% endfor %}

<!-- 分页导航 -->
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}
    <span class="current-page">{{ page_obj.number }}</span>
    <span class="total-pages">/{{ page_obj.paginator.num_pages }}</span>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
</div>
{% endblock %}
```

blog/templates/create_post.html
{% extends 'base_customer.html' %}
{% load static %}
{% block title %}车友圈/创作博客{% endblock %}
{% block content %}
<!-- blog/create_post.html -->
<style>
    .create-h1 {
        text-align:center;
    }

    .form-group1 {
        align-items: center;
        justify-content: space-between;
        margin-bottom: 20px;
    }

    .form-group1 label {
        font-weight: bold;
        font-size: 18px;
    }

    .form-group1 input[type="text"],
    .form-group1 select {
        padding: 5px;
        font-size: 16px;
    }

    .form-group1 button {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        float: right;
    }

    .form-group3 {
        align-items: center;
        justify-content: space-between;
        margin-top: 20px;
    }

    .form-group3 label {
        font-weight: bold;
        font-size: 18px;
    }

    .form-group3 input[type="file"] {
        font-size: 16px;
        margin-right: 10px;
    }

    .btn-back {
        background-color: green;
        color: white;
        border: none;
        padding: 8px 16px;
        border-radius: 5px;
        font-size: 16px;
        transition: background-color 0.3s ease;
        cursor: pointer;
        float: right;
    }

    .btn-back:hover {
        background-color: #006fe6;
    }
</style>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<h1 class="create-h1">发布新博客文章</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group1">
        {{ form.title.label_tag }}
        {{ form.title }}
        {{ form.tags.label_tag }}
        {{ form.tags }}
        <button type="submit">发布</button>
    </div>
    <div class="form-group2">
        {{ form.content }}
    </div>
    <div class="form-group3">
        {{ form.image.label_tag }}
        {{ form.image }}
        {{ form.video.label_tag }}
        {{ form.video }}
        <button type="button" class="btn btn-primary btn-back" onclick="window.location.href='{% url 'blog:post_list' %}'">回到博客列表</button>

    </div>
</form>
{% endblock %}

blog/templates/post_detail.html
{% extends 'base_customer.html' %}
{% load static %}
{% block title %}车友圈/博客详情{% endblock %}
{% block content %}
  <!-- blog/post_detail.html -->
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <style>
    .btn-back1 {
      background-color: green;
      color: white;
      border: none;
      padding: 8px 16px;
      border-radius: 5px;
      font-size: 16px;
      transition: background-color 0.3s ease;
      cursor: pointer;
      float: left;
    }

    .btn-back1:hover {
      background-color: #006fe6;
    }

    .btn-back2 {
      background-color: green;
      color: white;
      border: none;
      padding: 8px 16px;
      border-radius: 5px;
      font-size: 16px;
      transition: background-color 0.3s ease;
      cursor: pointer;
      float: right;
    }

    .btn-back2:hover {
      background-color: #006fe6;
    }
  </style>

<button type="button" class="btn btn-primary btn-back1" onclick="window.location.href='{% url 'blog:post_list' %}'">回到博客列表</button>
<button type="button" class="btn btn-secondary btn-back2" onclick="window.location.href='{% url 'blog:search_posts' %}'">返回继续搜索</button>


  <div class="post-container">
    <h2>
      <span style="font-size: 24px; font-weight: bold;">
        {{ post.title }}
      </span>
      <span style="margin-left: 10px;">
        {% for tag in post.tags.all %}
          <span style="color: red; font-size: 18px; font-weight: bold;">
            ## {{ tag.name }} ##
          </span>
        {% endfor %}
      </span>
    </h2>
    <div class="post-details">
      <p class="post-author" style="text-align: center; font-size: 20px; font-weight: bold;">
        <a href="{% url 'blog:user_profile' user_id=post.id %}">{{ post.author.username }}</a>
      </p>
      <p class="post-updated-at" style="text-align: center; color: #f00; font-size: 16px; font-weight: bold;">
        {{ post.updated_at }}
      </p>
    </div>
    <div class="post-content">{{ post.content|safe }}</div>
    {% if post.image %}
      <img src="{{ post.image.url }}" alt="{{ post.title }} Image">
    {% endif %}
    {% if post.video %}
      <video controls>
        <source src="{{ post.video.url }}" type="{{ post.video.content_type }}">
        Your browser does not support the video tag.
      </video>
    {% endif %}
  </div>

  <div class="d-flex flex-column align-items-center">
    <div class="text-center mb-2" style="font-size: 20px;">
      <a href="{% url 'blog:post_likes' post_id=post.id %}" style="font-weight: bold; margin-right: 20px;">
        <img src="{% static 'images/点赞.png' %}" class="btn-img"> {{ likes_count }}
      </a>
      <a href="{% url 'blog:comments_list' post_id=post.id %}" style="font-weight: bold; margin-right: 20px;">
        <img src="{% static 'images/评论.png' %}" class="btn-img"> {{ comments_count }}
      </a>
      <a href="#" style="font-weight: bold; margin-right: 20px;">
        <img src="{% static 'images/转发.png' %}" class="btn-img"> {{ shares }}
      </a>
    </div>
  </div>


  <div class="post-actions">
  {% if request.user.is_authenticated %}
    {% if request.user in post.likes.all %}
      <form method="post" action="{% url 'blog:unlike_post' post_id=post.id %}">
        {% csrf_token %}
        <button class="post-like-btn" type="submit">取消点赞</button>
      </form>
    {% else %}
      <form method="post" action="{% url 'blog:like_post' post_id=post.id %}">
        {% csrf_token %}
        <button class="post-like-btn" type="submit">点赞</button>
      </form>
    {% endif %}
  {% endif %}
  <form class="post-share-form" method="POST" action="{% url 'blog:share_post' post.id %}">
    {% csrf_token %}
    <button class="post-like-btn" type="submit">分享</button>
  </form>
</div>


{% endblock %}

blog/templates/post_list.html
{% extends 'base_customer.html' %}
{% load static %}
{% block title %}博客列表{% endblock %}
{% block content %}
<style>
  /* Styles for blog posts */
  .card {
    margin-bottom: 30px;
    border-radius: 10px;
    border: none;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  }
  .card .tag-badge {
    margin: 0 5px 5px 0;
  }
  .card-title {
    font-size: 1.5rem;
    color: #333;
    margin-bottom: 10px;
  }

  /* Styles for pagination */
  .pagination {
    margin: 30px 0;
  }
  .pagination a {
    padding: 5px 10px;
    border: 1px solid #ccc;
    color: #333;
    margin: 3px;
    font-weight: bold;
  }
  .pagination .current-page {
    background-color: #337ab7;
    color: #fff;
    border-color: #337ab7;
  }

  /* Styles for buttons */
  .btn-img {
    max-width: 50px;
    max-height: 50px;
  }
  .btn-primary {
    background-color: #007bff;
    border-color: #007bff;
    margin-right: 10px;
  }

  /* Custom styles */
  .custom-header {
    margin-bottom: 50px;
    text-align: center;
    position: relative;
  }
  .custom-header h1 {
    font-size: 2.5rem;
  }
  .custom-header p {
    font-size: 1.2rem;
  }

  .btn-back1 {
      position: absolute;
      left: 200px;
  }

  .btn-back2 {
      position: absolute;
      right: 200px;
  }

  .list-group {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
        gap: 20px;
        margin-top: 20px;
        list-style: none;
        padding: 0;
  }

    .list-group-item {
        background-color: #f8f9fa;
        border: none;
        border-radius: 5px;
        padding: 20px;
        position: relative;
        height: 180px;
        width: 500px;
        margin: 0 auto;
    }

    .list-group-item h4 {
        font-size: 20px;
        margin-bottom: 10px;
        color: #007bff;
    }

    .list-group-item p {
        font-size: 16px;
        margin-bottom: 10px;
        line-height: 1.5;
        overflow: hidden;
        text-overflow: clip;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        width: 20em;
    }

    .list-group-item a {
        position: absolute;
        bottom: 20px;
        right: 20px;
        font-weight: bold;
        color: #007bff;
    }

    .list-group-item small {
        font-size: 14px;
        color: #6c757d;
        position: absolute;
        bottom: 20px;
        left: 20px;
    }

    .list-group-item .badge {
        margin-right: 10px;
        font-size: 18px;
        font-weight: bold;
        background-color: #6cadb5;
    }
</style>

<!-- Custom header -->
<div class="custom-header">
  <a href="{% url 'blog:create_post' %}" class="btn-back1"><img src="{% static 'images/create.png' %}" class="btn-img">创作</a>
  <a href="{% url 'blog:search_posts' %}" class="btn-back2"><img src="{% static 'images/search.png' %}" class="btn-img">搜索</a>
  <h1>欢迎来到博客列表</h1>
  <p>在这里你可以查看所有博客文章，也可以根据标签进行筛选。</p>
</div>

<!-- 标签筛选和超链接按钮的排版 -->
<div class="my-4" style="text-align: center;">
  <form method="GET" action="{% url 'blog:post_list' %}" class="form-inline mb-4">
    <label for="id_tag" class="mr-2" style="font-size: 1.2em;">筛选标签：</label>
    <select name="tag" id="id_tag" class="form-control mr-3" style="font-size: 1.2em;">
      <option value="">全部</option>
      {% for tag in tags %}
        <option value="{{ tag.slug }}" {% if tag.slug == request.GET.tag %}selected{% endif %}>{{ tag.name }}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary mr-3" style="font-size: 1.2em;color:#ffffff">筛选</button>
  </form>
</div>

<!-- 所有博客文章 -->
<ul class="list-group">
  {% for post in page_obj %}
  <li class="list-group-item">
    <h4 style="float: left; margin-right: 10px; clear: both;">{{ post.title }}</h4>
    {% if post.tags.all %}
      <div style="float: right;">
        {% for tag in post.tags.all %}
        <span class="badge badge-secondary">{{ tag }}</span>
        {% endfor %}
      </div>
    {% endif %}
    <p style="clear: both;">{{ post.content|striptags }}</p>
    <a href="{% url 'blog:post_detail' post_id=post.id %}">查看详细信息</a>
    <small class="text-muted">作者：{{ post.author }}，发布时间：{{ post.created_at|date:"Y-m-d H:i:s" }}</small>
  </li>
</ul>
{% empty %}
<div class="col-lg-8 mx-auto">
  <p>暂无博客文章。</p>
</div>
{% endfor %}

<div class="pagination pt-3" style="text-align: center;">
  {% if page_obj.has_previous %}
  <button type="button" class="btn btn-link page-link" onclick="window.location.href='?tag={{ request.GET.tag }}&page=1'">&laquo; 首页</button>
  <button type="button" class="btn btn-link page-link" onclick="window.location.href='?tag={{ request.GET.tag }}&page={{ page_obj.previous_page_number }}'">上一页</button>
  {% endif %}

  {% for page in page_obj.paginator.page_range %}
  {% if page_obj.number == page %}
  <button type="button" class="btn btn-primary page-link current-page" onclick="window.location.href='?tag={{ request.GET.tag }}&page={{ page }}'">{{ page }}</button>
  {% else %}
  <button type="button" class="btn btn-link page-link" onclick="window.location.href='?tag={{ request.GET.tag }}&page={{ page }}'">{{ page }}</button>
  {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
  <button type="button" class="btn btn-link page-link" onclick="window.location.href='?tag={{ request.GET.tag }}&page={{ page_obj.next_page_number }}'">下一页</button>
  <button type="button" class="btn btn-link page-link" onclick="window.location.href='?tag={{ request.GET.tag }}&page={{ page_obj.paginator.num_pages }}'">末页 &raquo;</button>
  {% endif %}
</div>

{% endblock %}

blog/templates/user_profile.html
{% extends 'base_customer.html' %}

{% block title %}车友圈/个人主页{% endblock %}

{% block content %}
<style>
  .container-h1 {
    text-align: center;
  }

  .container-h2 {
    text-align: center;
  }

  .container-p {
    text-align: center;
  }

  h1, h2, h3 {
    margin-top: 30px;
    margin-bottom: 10px;
  }

  ul {
    list-style: none;
    padding: 0;
  }

  li {
    margin-bottom: 10px;
  }

  .btn-primary1 {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 8px 16px;
    border-radius: 5px;
    font-size: 16px;
    transition: background-color 0.3s ease;
    cursor: pointer;
  }

  .btn-primary1:hover {
    background-color: #006fe6;
  }

  .btn-primary {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 8px 16px;
    border-radius: 5px;
    font-size: 16px;
    transition: background-color 0.3s ease;
    cursor: pointer;
    position: absolute;
    top: 160px;
    right: 20px;
    transform: translateY(-50%);
  }

  .btn-primary:hover {
    background-color: #006fe6;
  }

  .btn-group {
    text-align:center;
    justify-content: space-between;
    align-items: center;
    /* 添加其他自定义样式 */
  }

  .btn-group a {
    font-size: 16px;
    color: #fff;
    text-decoration: none;
    /* 添加其他自定义样式 */
  }

  .list-group {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
        gap: 20px;
        margin-top: 20px;
        list-style: none;
        padding: 0;
    }

    .list-group-item {
        background-color: #f8f9fa;
        border: none;
        border-radius: 5px;
        padding: 20px;
        position: relative;
        height: 180px;
    }

    .list-group-item h4 {
        font-size: 20px;
        margin-bottom: 10px;
        color: #007bff;
    }

    .list-group-item p {
        font-size: 16px;
        margin-bottom: 10px;
        line-height: 1.5;
        overflow: hidden;
        text-overflow: clip;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        width: 6em;
    }

    .list-group-item a {
        position: absolute;
        bottom: 50px;
        right: 20px;
        font-weight: bold;
        color: #007bff;
    }

    .list-group-item small {
        font-size: 14px;
        color: #6c757d;
        position: absolute;
        bottom: 20px;
        left: 20px;
    }

    .list-group-item .badge {
        margin-right: 10px;
        font-size: 18px;
        font-weight: bold;
        background-color: #6cadb5;
    }
</style>

<div class="container-lg">
    <div class="col-md-4">
          {% if request.user != user %}
            {% if request.user in user.get_followers.all %}
              <form method="post" action="{% url 'blog:follow_user' user_id=user.id %}">
                {% csrf_token %}
                <button type="submit" class="btn-primary">取消关注</button>
              </form>
            {% else %}
              <form method="post" action="{% url 'blog:follow_user' user_id=user.id %}">
                {% csrf_token %}
                <button type="submit" class="btn-primary">关注</button>
              </form>
            {% endif %}
          {% endif %}
    </div>

    <h1 class="container-h1">{{ user.username }}的个人主页</h1>
    <div class="row">
      <div>
        <div class="btn-group">
          <a class="btn btn-primary1" href="{% url 'blog:following_list' user_id=user.id %}">关注&nbsp;{{ following.count }}</a>
          <a class="btn btn-primary1" href="{% url 'blog:follower_list' user_id=user.id %}">粉丝&nbsp;{{ followers.count }}</a>
        </div>

        <!-- 显示用户发表的文章 -->
        <h2 class="container-h2">发表的文章：</h2>
        {% if posts %}
            <ul class="list-group">
              {% for post in posts %}
              <li class="list-group-item">
                <h4 style="float: left; margin-right: 10px; clear: both;">{{ post.title }}</h4>
                {% if post.tags.all %}
                  <div style="float: right;">
                    {% for tag in post.tags.all %}
                    <span class="badge badge-secondary">{{ tag }}</span>
                    {% endfor %}
                  </div>
                {% endif %}
                <p style="clear: both;">{{ post.content|striptags }}</p>
                <a href="{% url 'blog:post_detail' post_id=post.id %}">查看详细信息</a>
                <small class="text-muted">作者：{{ post.author }}，发布时间：{{ post.created_at|date:"Y-m-d H:i:s" }}</small>
              </li>
              {% endfor %}
            </ul>
        {% else %}
          <p class="container-p">还没有发表文章</p>
        {% endif %}
      </div>
    </div>
</div>
{% endblock %}